# Generated by Django 3.1.2 on 2020-10-24 15:51

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201024_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tasks.models.saveTaskPhoto),
        ),
    ]
