# Generated by Django 3.1.2 on 2020-10-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_thumbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='categorie',
            new_name='category',
        ),
    ]
