# Generated by Django 3.1.2 on 2020-11-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201027_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
