export const SIGN_UP_CONTAINER="SignUpContainer"
export const SIGN_IN_CONTAINER="SignInContainer"
export const GET_CODE_CONTAINER="GetCodeContainer"
export const MEAN_MAIL="email"
export const MEAN_PHONE="phone"