version: "3"

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    environment:
      - DB_HOST=postgres
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - postgres
  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password