# Generated by Django 3.1.2 on 2020-10-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_onetimepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='isValid',
            field=models.BooleanField(default=True),
        ),
    ]
