# Generated by Django 3.1.2 on 2020-10-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201014_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='last_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
