export default {
    titleSignUp: "Sign Up",
    titleSignIn: "Sign In",
    titleGetCode: " Get Code",
    inputEmailPlaceholder: "emailexample@email.com",
    inputPhonePlaceholder: "00 00 00 00 00",
    inputUserPlaceholder: "Username",
    textAlreadyCount: "already a count ? ",
    textAlreadyCount2: "I haven't received my code yet ? ",
    linkAlreadyCount: "get my code",
    textAlreadyCode: "already received your code ? ",
    linkAlreadyCode: "sign in",
    textSignUp: "not registered ? ",
    linkSignUp: "sign up",
    btnSignUp: "Sign Up",
    btnGetCode: "Send",
    btnSignIn: "Sign In",
    email: "Email",
    phone: "Phone",
    errorMessagePseudo: "This username is already use. Choose another",
    errorMessageMail: "Email address does not appear to be valid",
    errorMessagePhone: "The phone number does not appear to be valid",
}