export default {
    easy: "easy",
    medium: "medium",
    difficult: "difficult",
    sport: "sport",
    wellBeing: "well-being",
    study: "study",
    creativity: "creativity",
    creationTitleCategory: "Category",
    creationTitleDifficulty: "Difficulty",
    creationIndicationCategory: "select a category",
    creationIndicationDifficulty: "select a difficulty",
    creationTitleTitle: "Title",
    creationIndicationTitle: "select a title",
    creationTitleDuration: "Duration",
    creationIndicationDuration: "select a Duration",
    creationTitleFrequency: "Frequency",
    creationIndicationFrequency: "select a Frequency",
    hours: "hours",
    minutes: "minutes",
    days: "days",
    weeks: "weeks",
}