export default {
    titleSignUp:"Inscription",
    titleSignIn:"Connexion",
    titleGetCode:"Obtenir code",
    inputEmailPlaceholder:"mailexemple@mail.com",
    inputPhonePlaceholder:"00 00 00 00 00",
    inputUserPlaceholder:"nom d'utilisateur",
    textAlreadyCount:"déjà inscrit ? ",
    textAlreadyCount2:"pas encore recu mon code ? ",
    linkAlreadyCount:"recevoir mon code",
    textAlreadyCode:"déja recu mon code ? ",
    linkAlreadyCode:"je me connecte",
    textSignUp:"pas encore inscrit ? ",
    linkSignUp:"je m'inscris",
    btnSignUp:"Je m'inscris",
    btnGetCode:"Envoyer",
    btnSignIn:"Connexion",
    email:"Email",
    phone:"Telephone"
}